# menu.yml
# used by Parallel::Site::Menu


- '&#8962': /
#- forking: 
- 
- fork(): /fork
- threads:
  - threads pragma: /threads
  - threads::shared: /threads-shared
- Perl Multi-Core Engine:
  - MCE: /mce
  - MCE::Shared: /mce-shared
- FAQ:   /faq
- '&#128712': /about
